defmodule Orbit.Ocs.Utilities.Stations do
  @spec ocs_to_gtfs(String.t() | nil) :: String.t() | nil

  # RL
  # def ocs_to_gtfs("ALEWIFE YARD"), do: ""
  def ocs_to_gtfs("ALEWIFE"), do: "place-alfcl"
  def ocs_to_gtfs("DAVIS SQUARE"), do: "place-davis"
  def ocs_to_gtfs("PORTER SQUARE"), do: "place-portr"
  def ocs_to_gtfs("HARVARD SQUARE"), do: "place-harsq"
  def ocs_to_gtfs("CENTRAL SQUARE"), do: "place-cntsq"
  def ocs_to_gtfs("KENDALL/MIT"), do: "place-knncl"
  def ocs_to_gtfs("CHARLES/MGH"), do: "place-chmnl"
  def ocs_to_gtfs("PARK STREET [R]"), do: "place-pktrm"
  def ocs_to_gtfs("DOWNTOWN CROSSING R"), do: "place-dwnxg"
  def ocs_to_gtfs("SOUTH STATION"), do: "place-sstat"
  def ocs_to_gtfs("BROADWAY"), do: "place-brdwy"
  def ocs_to_gtfs("ANDREW SQUARE"), do: "place-andrw"
  # def ocs_to_gtfs("CABOT YARD"), do: ""
  def ocs_to_gtfs("JFK/ UMASS ASH"), do: "place-jfk"
  def ocs_to_gtfs("SAVIN HILL"), do: "place-shmnl"
  def ocs_to_gtfs("FIELDS CORNER"), do: "place-fldcr"
  def ocs_to_gtfs("SHAWMUT"), do: "place-smmnl"
  def ocs_to_gtfs("ASHMONT"), do: "place-asmnl"
  # def ocs_to_gtfs("CODMAN YARD"), do: ""
  def ocs_to_gtfs("JFK/ UMASS BRT"), do: "place-jfk"
  def ocs_to_gtfs("NORTH QUINCY"), do: "place-nqncy"
  def ocs_to_gtfs("WOLLASTON"), do: "place-wlsta"
  def ocs_to_gtfs("QUINCY CENTER"), do: "place-qnctr"
  def ocs_to_gtfs("QUINCY ADAMS"), do: "place-qamnl"
  def ocs_to_gtfs("BRAINTREE"), do: "place-brntn"
  # def ocs_to_gtfs("BRAINTREE STORAGE"), do: ""
  # def ocs_to_gtfs("CADDIGAN YARD"), do: ""

  # OL
  # def ocs_to_gtfs("OAK GROVE STORAGE"), do: ""
  def ocs_to_gtfs("OAK GROVE"), do: "place-ogmnl"
  def ocs_to_gtfs("MALDEN CENTER"), do: "place-mlmnl"
  # def ocs_to_gtfs("WELL YARD N"), do: ""
  def ocs_to_gtfs("WELLINGTON"), do: "place-welln"
  # def ocs_to_gtfs("WELL YARD S"), do: ""
  def ocs_to_gtfs("ASSEMBLY"), do: "place-astao"
  def ocs_to_gtfs("SULLIVAN SQUARE"), do: "place-sull"
  def ocs_to_gtfs("COMMUNITY COLLEGE"), do: "place-ccmnl"
  def ocs_to_gtfs("NORTH STATION"), do: "place-north"
  def ocs_to_gtfs("HAYMARKET"), do: "place-haecl"
  def ocs_to_gtfs("STATE STREET"), do: "place-state"
  def ocs_to_gtfs("DOWNTOWN CROSSING"), do: "place-dwnxg"
  def ocs_to_gtfs("CHINATOWN"), do: "place-chncl"
  def ocs_to_gtfs("TUFTS MEDICAL CTR"), do: "place-tumnl"
  def ocs_to_gtfs("BACK BAY/SOUTH END"), do: "place-bbsta"
  def ocs_to_gtfs("MASS AVE"), do: "place-masta"
  def ocs_to_gtfs("RUGGLES"), do: "place-rugg"
  def ocs_to_gtfs("ROXBURY CROSSING"), do: "place-rcmnl"
  def ocs_to_gtfs("JACKSON SQUARE"), do: "place-jaksn"
  def ocs_to_gtfs("STONY BROOK"), do: "place-sbmnl"
  def ocs_to_gtfs("GREEN STREET"), do: "place-grnst"
  def ocs_to_gtfs("FOREST HILLS"), do: "place-forhl"
  # def ocs_to_gtfs("FOREST HILLS YARD"), do: ""

  # BL
  # def ocs_to_gtfs("WONDERLAND YARD"), do: ""
  def ocs_to_gtfs("WONDERLAND"), do: "place-wondl"
  def ocs_to_gtfs("REVERE BEACH"), do: "place-rbmnl"
  def ocs_to_gtfs("BEACHMONT"), do: "place-bmmnl"
  def ocs_to_gtfs("SUFFOLK DOWNS"), do: "place-sdmnl"
  # def ocs_to_gtfs("ORIENT HEIGHTS YARD"), do: ""
  def ocs_to_gtfs("ORIENT HEIGHTS"), do: "place-orhte"
  def ocs_to_gtfs("WOOD ISLAND"), do: "place-wimnl"
  def ocs_to_gtfs("AIRPORT"), do: "place-aport"
  def ocs_to_gtfs("MAVERICK SQUARE"), do: "place-mvbcl"
  def ocs_to_gtfs("AQUARIUM"), do: "place-aqucl"
  def ocs_to_gtfs("STATE STREET [B]"), do: "place-state"
  def ocs_to_gtfs("GOVERNMENT CENTER"), do: "place-gover"
  def ocs_to_gtfs("BOWDOIN"), do: "place-bomnl"
  # def ocs_to_gtfs("BOWDOIN STORAGE"), do: ""
  def ocs_to_gtfs(_), do: nil
end
