export type IconName =
  | "back"
  | "blue-line"
  | "clipboard"
  | "clock"
  | "feedback"
  | "help"
  | "info"
  | "logo"
  | "magnifying-glass"
  | "menu"
  | "red-line"
  | "shield"
  | "sign-out"
  | "warning-circle";
