# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
import Config

config :orbit, Orbit.Repo,
  # credentials are loaded in runtime.exs
  pool_size: 10

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :orbit, OrbitWeb.Endpoint,
  server: true,
  cache_static_manifest: "priv/static/cache_manifest.json"

config :logger, level: :info

config :ehmon, :report_mf, {:ehmon, :info_report}

# diskusage_logger calls disksup,
# which by default uses df flags that aren't available on alpine's busybox.
# this tells disksup to use different df flags
config :os_mon, disksup_posix_only: true
